apps/home/__init__.py
from flask import Blueprint
home= Blueprint("home",__name__)
from apps.home import views

apps/home/views.py
from flask import render_template,redirect

from apps.home import home

@home.route('/')
def index():
    return redirect("/")

apps/templates/401.html
{% extends "base.html" %}
{% block title %}401{% endblock %}
{% block body %}
  <h1 class="my-5 ml-5">Sorry,该网页给狗叼走了</h1>

  <!-- <p><a href="{{ url_for('home.index') }}">主页</a> -->
{% endblock %}

apps/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

apps/templates/base.html
<!doctype html>
<html lang="en">

    <head>
        <title>
            {% block title %}
            Base
            {% endblock %}
        </title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
              integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
              crossorigin="anonymous">
        <link rel="shortcut icon"
              href="{{ url_for('static', filename='favicon.ico') }}">
        <!-- <link rel="stylesheet"
              href="{{ url_for('static',filename='css/style.css') }}"> -->
        {% block style %}

        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand ml-3 mr-3"
               href="/">云打印</a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse"
                 id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ml-2 mr-3">
                        <a class="nav-link"
                           href="{{ url_for('home.index') }}">主页
                            <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item ml-2 mr-3">
                        <a class="nav-link"
                           href="#">个人信息</a>
                    </li>
                    <li class="nav-item ml-2 mr-3">
                        <a class="nav-link"
                           href="{{ url_for('auth.upload') }}">上传文件</a>
                    </li>
                    <li class="nav-item ml-2 mr-3">
                        <a class="nav-link"
                           href="#">历史记录</a>
                    </li>
                    <form class="form-inline ml-1 my-lg-0">
                        <input class="form-control mr-sm-2"
                               type="search"
                               placeholder="搜模板"
                               aria-label="Search">
                    </form>
                </ul>
                <nav class="nav justify-content-start ml-0">
                    {% if not current_user.is_authenticated %}
                    <a class="nav-link"
                       href="{{url_for('auth.login')}}">登录</a>
                    <a class="nav-link"
                       href="{{url_for('auth.register')}}">注册</a>
                    {% else %}
                    <a class="nav-link"
                       href="{{ url_for('auth.logout') }}">注销</a>
                    {% endif %}
            </div>
        </nav>
        </div>
        </nav>
        <div class="container-fluid">
            {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
            <div class="alert-message block-message error ">
                <a class="close alert alert-danger"
                   href="#">×</a>
                <ul class="flashes">
                    {% for msg in errors %}
                    <div class="alert alert-danger alert-dismissible fade show my-5"
                         role="alert">
                        <strong>Error:</strong> {{ msg }}.
                        <button type="button"
                                class="close"
                                data-dismiss="alert"
                                aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% endwith %}
            {% with successes=get_flashed_messages(category_filter=["success"]) %}
            {% if successes %}
            <ul class="flashes">
                {% for msg in successes %}
                <div class="alert alert-success alert-dismissible fade show my-5"
                     role="alert">
                    <strong>Success:</strong> {{ msg }}.
                    <button type="button"
                            class="close"
                            data-dismiss="alert"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}
        </div>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
        <small>
            <footer class='page-footer font-small indigo fixed-bottom'>
                <div id="footer"
                     class="footer-copyright text-center py-3">
                    {% block footer %}
                    &copy; Copyright 2018 by <a href="https://github.com/czfadmin">zfuChen</a>.
                    {% endblock %}
                </div>
            </footer>
        </small>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                crossorigin="anonymous"></script>
        <!-- <script type=text/javascript
                src="{{
                    url_for('static', filename='js/jquery.js') }}"></script> -->
        {% block scripts %}

        {% endblock %}
    </body>

</html>

apps/templates/login.html
{% extends "base.html" %}
{% block title %}
登录
{% endblock %}
{% block body %}
<div class="container">
    <form method="POST"
          class="my-5 ml-5 mr-5"
          action="{{ url_for('auth.login') }}">
        <div class="form-group">
            <label for="exampleInputEmail1">用户名</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            {{ form.password }}
        </div>
        <div class="form-check">
            {{ form.remember_me }}
            <label class="form-check-label"
                   for="dropdownCheck2">
                {{ form.remember_me.label }}
            </label>
        </div>
        <p class="my-4"><input type=submit
                   value="登录">
            <a href="{{ url_for('auth.register') }}"
               class="badge ml-3">注册</a>
            <a href="/"
               class="badge">返回</a>
        </p>
        <div class="dropdown-divider"></div>
        <small>
            <a class="dropdown-item text-sm-left"
               href="#"
               >Forgot password?</a>
        </small>


    </form>

</div>

{% endblock %}

apps/templates/logout.html
{% extends "base.html" %}
{% block title %}
注销
{% endblock %}

apps/templates/register.html
{% extends "base.html" %}
{% block title %}
用户注册
{% endblock %}
{% block body %}
<div class="container">
    <form method=post
          class="my-5 ml-5 mr-5"
          action="{{ url_for('auth.register') }}">

        <div class="form-group">
            <label for="exampleInputEmail1">用户名</label>
            {{ form.username }}

        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">邮箱</label>
            {{ form.email }}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            {{ form.password }}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">确认密码</label>
            {{ form.confirm }}
        </div>
        <p class="my-4"><input type=submit
                   value="注册">
            <a href="{{ url_for('auth.login') }}"
               class="badge ml-3">登录</a>
            <a href="/"
               class="badge">返回</a>
        </p>
    </form>
</div>

{% endblock %}

apps/templates/welcome.html
{% extends "base.html" %}
{% block title %}
Welcome
{% endblock %}
{% block body %}
<h4 class="my-5" >
    欢迎使用云打印
</h4>
{% endblock %}